#spring:
#  application:
#    name: account-service
#  couchbase:
#    connection-string: couchbase://localhost
#    user: admin
#    password: password
#
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
